export const desktopActions = [
  "nav.back",
  "nav.forward",
  "threads.collapse-all",
  "threads.filter",
  "project.add",
  "project.select",
  "project.expand",
  "project.collapse",
  "project.actions",
  "project.switch",
  "thread.new",
  "thread.open",
  "thread.archive",
  "thread.pin",
  "thread.actions",
  "thread.run-action",
  "workspace.open",
  "workspace.secondary",
  "workspace.popout",
  "product.menu",
  "connections.add",
  "connections.dismiss-banner",
  "composer.attach-menu",
  "composer.model",
  "composer.thinking",
  "composer.dictate",
  "composer.send",
  "composer.host",
  "composer.profile",
  "plugins.open-card",
  "automations.open-card",
  "debug.open-card",
  "landing.project-switcher",
  "diff.review",
  "terminal.close",
] as const;

export type DesktopAction = (typeof desktopActions)[number];
