export type { ArchivedThread, Message, Project, Thread } from '@howcode/shared/desktop-contracts.js'

export type View =
  | 'landing'
  | 'inbox'
  | 'code'
  | 'project'
  | 'thread'
  | 'gitops'
  | 'archived'
  | 'chat'
  | 'claw'
  | 'work'
  | 'automations'
  | 'settings'
  | 'extensions'
  | 'skills'
