import type { DesktopRequestChannel } from './desktop-ipc'

export type AppTransportOwner = 'desktop' | 'howcode-server' | 'pi-runtime'

export const desktopRequestChannelOwners = {
  getAppUpdateState: 'desktop',
  checkAppUpdate: 'desktop',
  installAppUpdate: 'desktop',
  restartAppUpdate: 'desktop',
  clearClipboardImages: 'desktop',
  getHowcodeServerState: 'desktop',
  getHowcodeInstanceManifest: 'howcode-server',
  getHowcodeRuntimeDiagnostics: 'howcode-server',
  refreshHowcodeServerState: 'desktop',
  listHowcodeRemoteEnvironments: 'desktop',
  saveHowcodeRemoteEnvironment: 'desktop',
  deleteHowcodeRemoteEnvironment: 'desktop',
  testHowcodeRemoteEnvironment: 'desktop',
  setActiveHowcodeRemoteEnvironment: 'desktop',
  clearActiveHowcodeRemoteEnvironment: 'desktop',
  getProjectRemoteEnvironmentAssignment: 'desktop',
  setProjectRemoteEnvironmentAssignment: 'desktop',
  getShellState: 'howcode-server',
  getProjectGitState: 'howcode-server',
  getProjectDiff: 'howcode-server',
  getProjectDiffStats: 'howcode-server',
  captureProjectDiffBaseline: 'howcode-server',
  listProjectCommits: 'howcode-server',
  searchPiPackages: 'pi-runtime',
  getConfiguredPiPackages: 'pi-runtime',
  installPiPackage: 'pi-runtime',
  removePiPackage: 'pi-runtime',
  searchPiSkills: 'pi-runtime',
  getConfiguredPiSkills: 'pi-runtime',
  installPiSkill: 'pi-runtime',
  removePiSkill: 'pi-runtime',
  startSkillCreatorSession: 'pi-runtime',
  continueSkillCreatorSession: 'pi-runtime',
  closeSkillCreatorSession: 'pi-runtime',
  pickComposerAttachments: 'desktop',
  readClipboardSnapshot: 'desktop',
  readClipboardFilePaths: 'desktop',
  readClipboardImage: 'desktop',
  getAttachmentKindsForPaths: 'desktop',
  listComposerAttachmentEntries: 'howcode-server',
  searchComposerAttachmentEntries: 'howcode-server',
  getComposerState: 'howcode-server',
  getComposerSlashCommands: 'howcode-server',
  getComposerSkills: 'howcode-server',
  getDictationState: 'desktop',
  listDictationModels: 'desktop',
  installDictationModel: 'desktop',
  removeDictationModel: 'desktop',
  transcribeDictation: 'desktop',
  getProjectThreads: 'howcode-server',
  getChatSidebarState: 'howcode-server',
  createChatGroup: 'howcode-server',
  listArtifacts: 'howcode-server',
  getArtifact: 'howcode-server',
  updateArtifact: 'howcode-server',
  editArtifact: 'howcode-server',
  listArtifactVersions: 'howcode-server',
  compileReactArtifact: 'howcode-server',
  getInboxThreads: 'howcode-server',
  getArchivedThreads: 'howcode-server',
  getThread: 'howcode-server',
  watchSession: 'howcode-server',
  invokeAction: 'pi-runtime',
  listTerminals: 'howcode-server',
  terminalOpen: 'howcode-server',
  terminalWrite: 'howcode-server',
  terminalResize: 'howcode-server',
  terminalClose: 'howcode-server',
  terminalSessionFileStat: 'howcode-server',
  terminalStatus: 'howcode-server',
  openExternal: 'desktop',
  openPath: 'desktop',
  saveTextToDownloads: 'desktop',
} satisfies Record<DesktopRequestChannel, AppTransportOwner>

export function getDesktopRequestChannelOwner(channel: DesktopRequestChannel) {
  return desktopRequestChannelOwners[channel]
}
