export const desktopActions = [
  "threads.collapse-all",
  "project.add",
  "project.select",
  "project.expand",
  "project.collapse",
  "project.open-in-file-manager",
  "project.reorder",
  "project.pin",
  "project.edit-name",
  "project.refresh-repo-origin",
  "project.archive-threads",
  "project.remove-project",
  "thread.new",
  "thread.open",
  "thread.archive",
  "thread.archive-many",
  "thread.restore",
  "thread.restore-many",
  "thread.delete",
  "thread.delete-many",
  "thread.pin",
  "workspace.commit",
  "workspace.commit-options",
  "composer.model",
  "composer.thinking",
  "composer.send",
  "composer.stop",
  "composer.dequeue",
  "composer.reload-settings",
  "inbox.mark-read",
  "inbox.dismiss",
  "settings.update",
  "pi-settings.update",
  "projects.import.scan",
  "projects.import.apply",
] as const;

export type DesktopAction = (typeof desktopActions)[number];
