import type { DesktopAction } from "./desktop-actions";

export const implementedDesktopActions = [
  "project.add",
  "project.select",
  "project.expand",
  "project.collapse",
  "project.open-in-file-manager",
  "project.reorder",
  "project.pin",
  "project.edit-name",
  "project.refresh-repo-origin",
  "project.archive-threads",
  "project.remove-project",
  "threads.collapse-all",
  "thread.pin",
  "thread.open",
  "thread.archive",
  "thread.archive-many",
  "thread.restore",
  "thread.restore-many",
  "thread.delete",
  "thread.delete-many",
  "thread.new",
  "composer.model",
  "composer.thinking",
  "composer.send",
  "composer.stop",
  "composer.dequeue",
  "composer.reload-settings",
  "inbox.mark-read",
  "inbox.dismiss",
  "workspace.commit",
  "workspace.commit-options",
  "settings.update",
  "projects.import.scan",
  "projects.import.apply",
] as const satisfies readonly DesktopAction[];

// These actions are intentionally accepted by the bridge but currently no-op on the
// backend until their renderer/desktop integrations are implemented.
export const unimplementedDesktopActions = [
  "threads.filter",
  "project.create-worktree",
  "thread.actions",
  "thread.run-action",
  "workspace.open",
  "workspace.open-options",
  "workspace.handoff",
  "workspace.popout",
  "connections.add",
  "connections.dismiss-banner",
  "composer.attach-menu",
  "composer.dictate",
  "composer.host",
  "plugins.open-card",
  "automations.open-card",
  "debug.open-card",
  "landing.project-switcher",
  "diff.review",
  "terminal.close",
] as const satisfies readonly DesktopAction[];
