import type { DesktopAction } from "./desktop-actions";

export const implementedDesktopActions = [
  "project.select",
  "project.expand",
  "project.collapse",
  "project.open-in-file-manager",
  "project.reorder",
  "project.edit-name",
  "project.archive-threads",
  "project.remove-project",
  "threads.collapse-all",
  "thread.pin",
  "thread.open",
  "thread.archive",
  "thread.restore",
  "thread.delete",
  "thread.new",
  "composer.model",
  "composer.thinking",
  "composer.send",
  "settings.update",
] as const satisfies readonly DesktopAction[];

// These actions are intentionally accepted by the bridge but currently no-op on the
// backend until their renderer/desktop integrations are implemented.
export const unimplementedDesktopActions = [
  "nav.back",
  "nav.forward",
  "threads.filter",
  "project.add",
  "project.actions",
  "project.create-worktree",
  "project.switch",
  "thread.actions",
  "thread.run-action",
  "workspace.open",
  "workspace.open-options",
  "workspace.handoff",
  "workspace.commit",
  "workspace.commit-options",
  "workspace.popout",
  "connections.add",
  "connections.dismiss-banner",
  "composer.attach-menu",
  "composer.dictate",
  "composer.host",
  "plugins.open-card",
  "automations.open-card",
  "debug.open-card",
  "landing.project-switcher",
  "diff.review",
  "terminal.close",
] as const satisfies readonly DesktopAction[];
